from starlette.config import Config
from core.configs.common import *

config = Config(".env")

APP_PORT                = config("APP_PORT", cast=int, default=9008)
SERVER_PATH             = config("SERVER_PATH", cast=str, default="ragflow.api.server")
AUTH_MODE               = config("AUTH_MODE", cast=str, default="credential")
GCP_PROJECT_ID          = config("GCP_PROJECT_ID", cast=str)
GCP_REGION              = config("GCP_REGION", cast=str)
DOCAI_PROCESSOR_NAME    = config("DOCAI_PROCESSOR_NAME", cast=str)
DOCAI_PROCESSOR_TYPE    = config("DOCAI_PROCESSOR_TYPE", cast=str)
GCP_SA_JSON_PATH        = config("GCP_SA_JSON_PATH", cast=str)
GEMINI_API_KEY          = config("GEMINI_API_KEY", cast=str, default="")
GCP_STORAGE_BUCKET      = config("GCP_STORAGE_BUCKET", cast=str)
BQ_DATASET_ID           = config("BQ_DATASET_ID", cast=str)
BQ_TABLE_ID             = config("BQ_TABLE_ID", cast=str)
DROP_EXISTING_TABLE     = config("DROP_EXISTING_TABLE", cast=bool, default=False)
EMBEDDING_MODEL         = config("EMBEDDING_MODEL", cast=str, default="text-embedding-005")
RAG_MODEL_NAME          = config("RAG_MODEL_NAME", cast=str, default="gemini-2.0-flash")
GEMINI_MODEL_NAME       = config("GEMINI_MODEL_NAME", cast=str, default="gemini-2.0-flash")
RAG_ENGINE_NAME         = config("RAG_ENGINE_NAME", cast=str, default="policy-guidelines-rag")
EMAIL_USERNAME          = config("EMAIL_USERNAME", cast=str)
EMAIL_PASSWORD          = config("EMAIL_PASSWORD", cast=str)
METADATA_TABLE_ID       = config("METADATA_TABLE_ID", cast=str)